version: "3.7"
services:
  screeps:
    build:
      context: .
    image: screeps
    restart: unless-stopped
    ports:
      - "21025:21025"
      - "21026:21026"
    volumes:
      - "./data:/screeps/data"
      - "./.screepsrc:/screeps/screepsrc"
